### ISSUE TITLE
getting error for constructing customer model using fromJson

### ISSUE THREAD

**Issue by gokuzhan** [RayOkaah/woocommerce#10]
```
E/flutter (18930): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'String'
E/flutter (18930): #0      new WooCustomerMetaData.fromJson (package:woocommerce/models/customer.dart:142:15)
E/flutter (18930): #1      new WooCustomer.fromJson.<anonymous closure> (package:woocommerce/models/customer.dart:91:68)
```

**Comment by RayOkaah** [comment]
This was an actual issue, and was fixed in the recently pushed update, thank you.
