### ISSUE TITLE
Error with getProductVariationById 

### ISSUE THREAD

**Issue by akfaisel** [RayOkaah/woocommerce#18]
Hi

I am working with Product Variations to get a list of all variations of a product and I get an error at 
`WooProductVariation variations = await wooCommerce.getProductVariationById(productId: 31);`
The reason is, since the variation parameter is not passed, it was converted to null and the query becomes **Query : products/31/variations/null**

I managed to pass empty string like below and the query becomes valid **Query : products/31/variations/**
`WooProductVariation variations = await wooCommerce.getProductVariationById(productId: 31, variationId: '');`

I get the following error
```
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'
E/flutter ( 5726): #0      WooCommerce.getProductVariationById (package:woocommerce/woocommerce.dart:537:53)
E/flutter ( 5726): <asynchronous suspension>
E/flutter ( 5726): #1      _MyHomePageState.getProducts (package:ecommerce/main.dart:66:56)
E/flutter ( 5726): <asynchronous suspension>
E/flutter ( 5726): #2      _MyHomePageState.initState (package:ecommerce/main.dart:76:5)
E/flutter ( 5726): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4702:58)
E/flutter ( 5726): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4538:5)
E/flutter ( 5726): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5892:14)
E/flutter ( 5726): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4589:16)
E/flutter ( 5726): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4280:5)
E/flutter ( 5726): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4543:5)
E/flutter ( 5726): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4538:5)
E/flutter ( 5726): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5892:14)
E/flutter ( 5726): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5892:14)
E/flutter ( 5726): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4589:16)
E/flutter ( 5726): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4737:11)
E/flutter ( 5726): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4280:5)
E/flutter ( 5726): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4543:5)
E/flutter ( 5726): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4728:11)
E/flutter ( 5726): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4538:5)
E/flutter ( 5726): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5892:14)
E/flutter ( 5726): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5892:14)
E/flutter ( 5726): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4589:16)
E/flutter ( 5726): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4737:11)
E/flutter ( 5726): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4280:5)
E/flutter ( 5726): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4543:5)
E/flutter ( 5726): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4728:11)
E/flutter ( 5726): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4538:5)
E/flutter ( 5726): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter ( 5726): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter ( 5726): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4589:16)
E/flutter ( 5726): #45     Element.rebuil
```
Please handle the null exception and the error above.

Please help.

**Comment by akfaisel** [comment]
I have managed to solve this myself. Please see my pull request and add a new function.

**Comment by RayOkaah** [comment]
Thanks. Just Seeing this as well. Your PR has been merged.
