### ISSUE TITLE
authenticateViaJWT returns rest_no_route

### ISSUE THREAD

**Issue by ChristianGiupponi** [RayOkaah/woocommerce#22]
I have tried to implement the authenticateViaJWT method following the docs but I get some errors.

This is my code:

```
import 'package:flutter/material.dart';
import 'package:woocommerce/woocommerce.dart';

WooCommerce woocommerce = WooCommerce(
  baseUrl: kWoocommerceBaseUrl,
  consumerKey: kWoocommerceConsumerKey,
  consumerSecret: kWoocommerceConsumerSecret,
);

class LoginPage extends StatefulWidget {
  static const routeName = '/login';

  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _emailController = new TextEditingController();
  final TextEditingController _passwordController = new TextEditingController();

  String _email;
  String _password;
  bool _isLoading = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: LoadingOverlay(
        isLoading: _isLoading,
        progressIndicator: isAndroid
            ? CircularProgressIndicator()
            : CupertinoActivityIndicator(),
        child: SafeArea(
          child: Container(
            padding: EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                Expanded(
                  child: Container(
                    child: Center(
                      child: Text(
                        'Login',
                        style: TextStyle(
                          fontSize: 30.0,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                ),
                Form(
                  key: _formKey,
                  child: _buildTextFields(),
                ),
                SizedBox(
                  height: 16.0,
                ),
                AmButton(
                  text: 'Login',
                  onPressed: () async {
                    if (_formKey.currentState.validate()) {
                      FocusScope.of(context).unfocus();

                      setState(() {
                        // _isLoading = true;
                      });

                      print(_email);
                      print(_password);

                      //Login - Returns the access token on success.

                      final token = await woocommerce.authenticateViaJWT(
                          username: _email, password: _password);

                      print(token);
                    }
                  },
                ),
                SizedBox(
                  height: 8.0,
                ),
                Expanded(
                  child: Container(),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildTextFields() {
    return Container(
      child: Column(
        children: <Widget>[
          Container(
            child: TextFormField(
              controller: _emailController,
              decoration: InputDecoration(labelText: 'Email'),
              validator: (value) => _checkEmailAddress(value),
            ),
          ),
          Container(
            child: TextFormField(
              controller: _passwordController,
              decoration: InputDecoration(labelText: 'Password'),
              obscureText: true,
              validator: (value) => _checkPassword(value),
            ),
          )
        ],
      ),
    );
  }

  bool _isValidEmailAddress(email) {
    return RegExp(
            r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+")
        .hasMatch(email);
  }

  String _checkEmailAddress(email) {
    if (email.isEmpty) {
      return 'Devi inserire la tua email';
    }

    if (!_isValidEmailAddress(email)) {
      return 'Devi inserire un indirizzo email valido';
    }

    setState(() {
      _email = email;
    });

    return null;
  }

  String _checkPassword(value) {
    if (value.isEmpty) {
      return 'Devi inserire la password';
    }

    setState(() {
      _password = value;
    });

    return null;
  }
}
```

the authenticateViaJWT method is used in a onPressed callback, here the code:

```
onPressed: () async {
                    if (_formKey.currentState.validate()) {
                      FocusScope.of(context).unfocus();

                      setState(() {
                        // _isLoading = true;
                      });

                      print(_email);
                      print(_password);

                      //Login - Returns the access token on success.

                      final token = await woocommerce.authenticateViaJWT(
                          username: _email, password: _password);

                      print(token);
                    }
                  },
```

as you can see nothing complicated.  
The problem is that when I press the button I get:

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: WooCommerce Error!
code: rest_no_route
message: No Path provides a match between the URL and the request mode
status: 404
#0      WooCommerce.authenticateViaJWT (package:woocommerce/woocommerce.dart:196:9)
<asynchronous suspension>
#1      _LoginPageState.build.<anonymous closure> (package:testwoocommerce/pages/login.dart:82:55)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
#8      PrimaryPointerGestureRecognizer.handleEven<…>
```

any idea?

**Comment by ChristianGiupponi** [comment]
Nevermind, the JWT plugin was not activated on my Wordpress installation
