### ISSUE TITLE
getProducts return 401

### ISSUE THREAD

**Issue by OjeanKOG** [RayOkaah/woocommerce#5]
Hello ! I am trying to use this plugin in my flutter app.
But I have an error when I test

products = await wooCommerce.getProducts ();
I have a 401 error: invalid signature

When I do the test with postman, there is no problem, but in the app, no.
the consumerKey and consumerSecret are correct

**Comment by OjeanKOG** [comment]
Should you first be identified before being able to retrieve the list of products?

WOOCOMMERCE LOG: oauth token =:

**Comment by RayOkaah** [comment]
Thanks fixed. Check the latest Pub 0.9.6.

**Comment by OjeanKOG** [comment]
Great !

**Comment by OjeanKOG** [comment]
Hello... 
I allow myself to reopen the subject because I still have some concerns

I don't know if this is due to the plugin.

When I test them on an emulator, the problem persists. And when it's on a real phone I have a 403 error.
On postman, everything works fine !

**Comment by RayOkaah** [comment]
This likely has to do with your websites firewall, security configuration, or conflicting plugins. Do check this https://wordpress.org/support/topic/wp-rest-api-users-endpoint-returns-403-error/

**Comment by OjeanKOG** [comment]
Thank you for the answer. I did all the checks and configurations. All is correct. But I noticed that in Http, you had to use Oauth1.0 as authorization
This may be the problem. Have you considered this?

**Comment by akfaisel** [comment]
Hi,
Thanks for a great plugin.

I can get the Bearer token successfully in Auth section and I can login the user but it doesn't work on getProducts. I'm getting the following error message. I have tried with both 0.9.6 and 0.9.7 but gives the same error.

Please help.

```
E/flutter ( 4535): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: Exception: WooCommerce Error!
E/flutter ( 4535): code: woocommerce_rest_authentication_error
E/flutter ( 4535): message: Invalid signature - provided signature does not match.
E/flutter ( 4535): status: 401
E/flutter ( 4535): #0      WooCommerce._handleHttpError (package:woocommerce/woocommerce.dart:1557:9)
E/flutter ( 4535): #1      WooCommerce.get (package:woocommerce/woocommerce.dart:1634:7)
E/flutter ( 4535): <asynchronous suspension>
E/flutter ( 4535): #2      WooCommerce.getProducts (package:woocommerce/woocommerce.dart:457:28)
E/flutter ( 4535): #3      _MyHomePageState.getData (package:ecommerce/main.dart:58:42)
E/flutter ( 4535): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 4535): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4535): #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 4535): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 4535): #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 4535): #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 4535): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 4535): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 4535): #12     WooCommerce.isCustomerLoggedIn (package:woocommerce/woocommerce.dart)
E/flutter ( 4535): #13     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 4535): #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4535): #15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 4535): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 4535): #17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 4535): #18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 4535): #19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 4535): #20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 4535): #21     LocalDatabaseService.getSecurityToken (package:woocommerce/utilities/local_db.dart)
E/flutter ( 4535): #22     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 4535): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4535): #24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 4535): #25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 4535): #26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 4535): #27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 4535): #28     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 4535): #29     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 4535): #30     FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart)
E/flutter ( 4535): #31     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 4535): #32     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4535): #33     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 4535): #34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 4535): #35     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 4535): #36     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 4535): #37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 4535): #38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 4535): #39     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter ( 4535): #40     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 4535): #41     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4535): #42     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 4535): #43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 4535): #44     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 4535): #45     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 4535): #46     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 4535): #47     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 4535): #48     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 4535): #49     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 4535): #50     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 4535): #51     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 4535): #52     _st
```
